name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Build the dealership landing page
      - name: Install dependencies
        run: |
          cd dealership-landing
          npm install

      - name: Build dealership landing
        run: |
          cd dealership-landing
          npm run build

      - name: Copy to deployment folder
        run: |
          rm -rf ai-agent-car-dealerships/*
          cp -r dealership-landing/dist/* ai-agent-car-dealerships/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
