name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies for main site
        run: npm ci

      - name: Build main site
        run: npm run build

      - name: Install dependencies for dealership landing
        run: |
          cd dealership-landing
          npm ci

      - name: Build dealership landing
        run: |
          cd dealership-landing
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare deployment directory
        run: |
          mkdir -p _site
          cp -r dist/* _site/
          cp contact.html _site/

          # Copy privacy and terms pages from root
          cp privacy.html _site/privacy.html
          cp terms.html _site/terms.html

          # Create dealership landing page
          mkdir -p _site/ai-agent-car-dealerships
          cp -r dealership-landing/dist/* _site/ai-agent-car-dealerships/

          touch _site/.nojekyll
          echo "=== DEPLOYMENT STRUCTURE ==="
          find _site -type f -name "*.html"
          echo "=== END STRUCTURE ==="

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
