name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies for main site
        run: npm ci

      - name: Build main site
        run: npm run build

      - name: Install dependencies for dealership landing
        run: |
          cd dealership-landing
          npm ci

      - name: Build dealership landing
        run: |
          cd dealership-landing
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare deployment directory
        run: |
          mkdir -p _site
          cp -r dist/* _site/

          # Copy SEO files to root
          cp sitemap.xml _site/sitemap.xml
          cp robots.txt _site/robots.txt

          # Copy main pages with SEO headers
          cp contact.html _site/contact.html
          cp privacy.html _site/privacy.html
          cp terms.html _site/terms.html

          # Create dealership landing page
          mkdir -p _site/ai-agent-car-dealerships
          cp -r dealership-landing/dist/* _site/ai-agent-car-dealerships/

          # Copy favicon and manifest files (if they exist)
          [ -f favicon.ico ] && cp favicon.ico _site/favicon.ico
          [ -f favicon-16x16.png ] && cp favicon-16x16.png _site/favicon-16x16.png
          [ -f favicon-32x32.png ] && cp favicon-32x32.png _site/favicon-32x32.png
          [ -f apple-touch-icon.png ] && cp apple-touch-icon.png _site/apple-touch-icon.png
          [ -f site.webmanifest ] && cp site.webmanifest _site/site.webmanifest

          # Copy logo to root for structured data
          [ -f public/logo.png ] && cp public/logo.png _site/logo.png

          # Create .nojekyll to prevent GitHub Pages from processing
          touch _site/.nojekyll

          echo "=== DEPLOYMENT STRUCTURE ==="
          find _site -type f -name "*.html" | head -20
          find _site -type f -name "*.xml"
          find _site -type f -name "*.txt"
          find _site -type f -name "*.png" | head -10
          find _site -type f -name "*.ico"
          find _site -type f -name "*.webmanifest"
          echo "=== END STRUCTURE ==="

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
